### ISSUE TITLE
Agregar nueva fuente

### ISSUE THREAD

**Issue by yupanquidev** [HustavoJhon/trickxyz#7]
**OPCIONES**:
- [x] [Poppins](https://fontsource.org/fonts/poppins)
- [x] [Onest](https://fontsource.org/fonts/onest)
- [x] [Geist](https://fontsource.org/fonts/geist-sans)
- [x] [Literata](https://fontsource.org/fonts/literata)

**Comment by HustavoJhon** [comment]
Añade dos fuentes nuevas.
